"""
Historical arcs (migration + trade + exchange routes) and empire footprints.
Coordinates and dates are approximate consensus points.
"""

# Migration & exchange arcs. Each arc is drawn from year_start to year_end.
ARCS = [
    {"id": "arc-beringia", "label": "Beringia Crossing",
     "start_year": -20000, "end_year": -12000, "category": "land",
     "start_lat": 62.0, "start_lng": 135.0,
     "end_lat": 61.0, "end_lng": -150.0,
     "color": "#6B8E23"},
    {"id": "arc-out-africa", "label": "Out of Africa (Neolithic diffusion)",
     "start_year": -50000, "end_year": -10000, "category": "civilizations",
     "start_lat": 5.0, "start_lng": 38.0,
     "end_lat": 40.0, "end_lng": 30.0,
     "color": "#D4AF37"},
    {"id": "arc-austronesian", "label": "Austronesian Expansion",
     "start_year": -3000, "end_year": 1200, "category": "civilizations",
     "start_lat": 23.7, "start_lng": 121.0,
     "end_lat": -17.6, "end_lng": -149.4,
     "color": "#D4AF37"},
    {"id": "arc-silkroad-cn-rome", "label": "Silk Road (Chang'an → Rome)",
     "start_year": -130, "end_year": 1450, "category": "civilizations",
     "start_lat": 34.3, "start_lng": 108.9,
     "end_lat": 41.9, "end_lng": 12.5,
     "color": "#D4AF37"},
    {"id": "arc-silkroad-cn-samarkand", "label": "Silk Road (Chang'an → Samarkand)",
     "start_year": -130, "end_year": 1450, "category": "civilizations",
     "start_lat": 34.3, "start_lng": 108.9,
     "end_lat": 39.65, "end_lng": 66.97,
     "color": "#D4AF37"},
    {"id": "arc-viking-vinland", "label": "Norse to Vinland",
     "start_year": 985, "end_year": 1050, "category": "civilizations",
     "start_lat": 64.14, "start_lng": -21.94,
     "end_lat": 51.0, "end_lng": -55.5,
     "color": "#D4AF37"},
    {"id": "arc-columbian-e", "label": "Columbian Exchange (Europe → Americas)",
     "start_year": 1492, "end_year": 1800, "category": "pandemics",
     "start_lat": 37.3, "start_lng": -6.0,
     "end_lat": 19.43, "end_lng": -99.13,
     "color": "#8B0000"},
    {"id": "arc-columbian-w", "label": "Columbian Exchange (Americas → Europe)",
     "start_year": 1492, "end_year": 1800, "category": "technology",
     "start_lat": 19.43, "start_lng": -99.13,
     "end_lat": 37.3, "end_lng": -6.0,
     "color": "#4682B4"},
    {"id": "arc-slave-trade", "label": "Trans-Atlantic Slave Trade",
     "start_year": 1526, "end_year": 1867, "category": "pandemics",
     "start_lat": 6.5, "start_lng": 3.4,
     "end_lat": -12.97, "end_lng": -38.5,
     "color": "#8B0000"},
    {"id": "arc-industrial", "label": "Industrial Revolution Diffusion",
     "start_year": 1780, "end_year": 1900, "category": "technology",
     "start_lat": 53.48, "start_lng": -2.24,
     "end_lat": 40.44, "end_lng": -79.99,
     "color": "#4682B4"},
    {"id": "arc-apollo", "label": "Earth to Moon (Apollo 11)",
     "start_year": 1969, "end_year": 1972, "category": "technology",
     "start_lat": 28.57, "start_lng": -80.65,
     "end_lat": 0.67, "end_lng": 23.47,
     "color": "#4682B4"},
]

# Empire territorial footprints keyed by modern country name (as used by
# world-atlas 110m countries dataset). Approximate — for visualization only.
EMPIRES = [
    {"id": "emp-egypt", "name": "Ancient Egypt", "start_year": -3100, "end_year": -30,
     "countries": ["Egypt", "Sudan"], "color": "#D4AF37"},
    {"id": "emp-persia", "name": "Achaemenid Persia", "start_year": -550, "end_year": -330,
     "countries": ["Iran", "Iraq", "Turkey", "Egypt", "Syria", "Israel", "Jordan",
                   "Lebanon", "Afghanistan", "Turkmenistan", "Uzbekistan", "Tajikistan",
                   "Pakistan", "Armenia", "Azerbaijan", "Kuwait"],
     "color": "#D4AF37"},
    {"id": "emp-macedon", "name": "Alexander's Empire", "start_year": -336, "end_year": -323,
     "countries": ["Greece", "Turkey", "Iran", "Iraq", "Syria", "Egypt", "Israel",
                   "Jordan", "Lebanon", "Afghanistan", "Pakistan", "Uzbekistan",
                   "Turkmenistan", "Tajikistan"],
     "color": "#D4AF37"},
    {"id": "emp-rome-rep", "name": "Roman Republic", "start_year": -509, "end_year": -27,
     "countries": ["Italy", "France", "Spain", "Portugal", "Greece", "Croatia", "Slovenia",
                   "Albania", "Tunisia", "Turkey", "Syria"],
     "color": "#D4AF37"},
    {"id": "emp-rome-emp", "name": "Roman Empire", "start_year": -27, "end_year": 395,
     "countries": ["Italy", "France", "Spain", "Portugal", "United Kingdom", "Belgium",
                   "Netherlands", "Germany", "Switzerland", "Austria", "Greece", "Croatia",
                   "Slovenia", "Serbia", "Bosnia and Herz.", "Montenegro", "Albania",
                   "North Macedonia", "Bulgaria", "Romania", "Hungary", "Turkey", "Syria",
                   "Lebanon", "Israel", "Jordan", "Egypt", "Libya", "Tunisia", "Algeria",
                   "Morocco", "Cyprus"],
     "color": "#D4AF37"},
    {"id": "emp-han", "name": "Han China", "start_year": -206, "end_year": 220,
     "countries": ["China", "North Korea", "Vietnam"], "color": "#D4AF37"},
    {"id": "emp-byz", "name": "Byzantine Empire", "start_year": 395, "end_year": 1453,
     "countries": ["Turkey", "Greece", "Bulgaria", "Albania", "North Macedonia", "Cyprus",
                   "Syria", "Lebanon", "Israel", "Jordan", "Egypt", "Libya"],
     "color": "#D4AF37"},
    {"id": "emp-caliph", "name": "Islamic Caliphate (peak)", "start_year": 750, "end_year": 950,
     "countries": ["Saudi Arabia", "Iraq", "Iran", "Syria", "Jordan", "Israel", "Lebanon",
                   "Egypt", "Libya", "Tunisia", "Algeria", "Morocco", "Spain", "Portugal",
                   "Yemen", "Oman", "Turkmenistan", "Uzbekistan", "Afghanistan", "Pakistan"],
     "color": "#D4AF37"},
    {"id": "emp-tang", "name": "Tang China", "start_year": 618, "end_year": 907,
     "countries": ["China", "North Korea", "Vietnam", "Mongolia", "Kazakhstan", "Kyrgyzstan"],
     "color": "#D4AF37"},
    {"id": "emp-mongol", "name": "Mongol Empire", "start_year": 1206, "end_year": 1368,
     "countries": ["Mongolia", "China", "Russia", "Kazakhstan", "Kyrgyzstan", "Uzbekistan",
                   "Turkmenistan", "Tajikistan", "Afghanistan", "Iran", "Iraq", "Ukraine",
                   "Belarus", "Georgia", "Armenia", "Azerbaijan", "Turkey", "North Korea",
                   "South Korea"],
     "color": "#D4AF37"},
    {"id": "emp-mali", "name": "Mali Empire", "start_year": 1235, "end_year": 1670,
     "countries": ["Mali", "Senegal", "Guinea", "Mauritania", "Burkina Faso", "Niger", "Gambia"],
     "color": "#D4AF37"},
    {"id": "emp-inca", "name": "Inca Empire", "start_year": 1438, "end_year": 1533,
     "countries": ["Peru", "Ecuador", "Bolivia", "Chile", "Argentina", "Colombia"],
     "color": "#D4AF37"},
    {"id": "emp-aztec", "name": "Aztec Triple Alliance", "start_year": 1428, "end_year": 1521,
     "countries": ["Mexico"], "color": "#D4AF37"},
    {"id": "emp-ottoman", "name": "Ottoman Empire", "start_year": 1299, "end_year": 1922,
     "countries": ["Turkey", "Greece", "Bulgaria", "Serbia", "Bosnia and Herz.", "Albania",
                   "Montenegro", "North Macedonia", "Romania", "Hungary", "Syria", "Lebanon",
                   "Israel", "Jordan", "Iraq", "Saudi Arabia", "Yemen", "Egypt", "Libya",
                   "Tunisia", "Algeria", "Cyprus", "Kuwait"],
     "color": "#D4AF37"},
    {"id": "emp-spain", "name": "Spanish Empire", "start_year": 1492, "end_year": 1898,
     "countries": ["Spain", "Mexico", "Cuba", "Dominican Rep.", "Puerto Rico", "Guatemala",
                   "Honduras", "El Salvador", "Nicaragua", "Costa Rica", "Panama", "Colombia",
                   "Venezuela", "Ecuador", "Peru", "Bolivia", "Chile", "Argentina", "Paraguay",
                   "Uruguay", "Philippines"],
     "color": "#D4AF37"},
    {"id": "emp-british", "name": "British Empire", "start_year": 1707, "end_year": 1947,
     "countries": ["United Kingdom", "Ireland", "Canada", "United States of America",
                   "Australia", "New Zealand", "India", "Pakistan", "Bangladesh", "Sri Lanka",
                   "Myanmar", "Malaysia", "Singapore", "South Africa", "Nigeria", "Ghana",
                   "Kenya", "Uganda", "Tanzania", "Zimbabwe", "Zambia", "Egypt", "Sudan",
                   "Jamaica", "Guyana"],
     "color": "#D4AF37"},
    {"id": "emp-mughal", "name": "Mughal Empire", "start_year": 1526, "end_year": 1857,
     "countries": ["India", "Pakistan", "Bangladesh", "Afghanistan"], "color": "#D4AF37"},
    {"id": "emp-russia", "name": "Russian Empire", "start_year": 1721, "end_year": 1917,
     "countries": ["Russia", "Ukraine", "Belarus", "Estonia", "Latvia", "Lithuania",
                   "Finland", "Poland", "Georgia", "Armenia", "Azerbaijan", "Kazakhstan",
                   "Kyrgyzstan", "Turkmenistan", "Uzbekistan", "Tajikistan", "Moldova"],
     "color": "#D4AF37"},
    {"id": "emp-ussr", "name": "Soviet Union", "start_year": 1922, "end_year": 1991,
     "countries": ["Russia", "Ukraine", "Belarus", "Estonia", "Latvia", "Lithuania",
                   "Georgia", "Armenia", "Azerbaijan", "Kazakhstan", "Kyrgyzstan",
                   "Turkmenistan", "Uzbekistan", "Tajikistan", "Moldova"],
     "color": "#D4AF37"},
]


def list_arcs():
    return ARCS


def list_empires():
    return EMPIRES
