"""
Historical events dataset - carefully curated real historical events
Sources: Smithsonian, UNESCO, British Museum, Encyclopedia Britannica,
World History Encyclopedia, WHO archives, and national historical databases.

Each event has:
- id: unique id
- title: event name
- year: negative for BCE, positive for CE
- lat, lng: approximate geographic center
- category: civilizations | land | pandemics | technology
- region: geographic region name
- summary: 1-2 sentence factual overview
- source: short attribution
"""

EVENTS = [
    # =========================
    # LAND TRANSFORMATIONS
    # =========================
    {"id": "land-bering", "title": "Bering Land Bridge (Beringia) Traversed", "year": -20000,
     "lat": 65.5, "lng": -168.0, "category": "land", "region": "Beringia",
     "summary": "During the Last Glacial Maximum, sea levels fell ~120m exposing Beringia, a land bridge between Siberia and Alaska used by Paleo-Indians to enter the Americas.",
     "source": "Smithsonian Human Origins Program"},
    {"id": "land-doggerland", "title": "Doggerland Submerged", "year": -6200,
     "lat": 54.0, "lng": 2.5, "category": "land", "region": "North Sea",
     "summary": "The Storegga tsunami and rising post-glacial seas drowned Doggerland, a Mesolithic landmass connecting Britain to continental Europe.",
     "source": "British Museum / University of Bradford"},
    {"id": "land-sahara-green", "title": "Green Sahara Ends (Aridification)", "year": -3500,
     "lat": 23.0, "lng": 12.0, "category": "land", "region": "North Africa",
     "summary": "The African Humid Period ends: the once-lush Sahara, filled with lakes and pastoralists, desertifies, driving migration toward the Nile Valley.",
     "source": "Smithsonian Human Origins / NASA GISS"},
    {"id": "land-thera", "title": "Minoan Eruption of Thera (Santorini)", "year": -1600,
     "lat": 36.4, "lng": 25.4, "category": "land", "region": "Aegean",
     "summary": "One of the largest volcanic eruptions in recorded history devastated the Minoan settlement of Akrotiri and darkened skies across the Mediterranean.",
     "source": "British School at Athens"},
    {"id": "land-vesuvius", "title": "Eruption of Mount Vesuvius", "year": 79,
     "lat": 40.82, "lng": 14.43, "category": "land", "region": "Italy",
     "summary": "Vesuvius buried Pompeii and Herculaneum under pyroclastic surges, preserving Roman daily life in ash for archaeology.",
     "source": "Soprintendenza Pompei"},
    {"id": "land-krakatoa", "title": "Krakatoa Eruption", "year": 1883,
     "lat": -6.10, "lng": 105.42, "category": "land", "region": "Sunda Strait",
     "summary": "The cataclysmic 1883 eruption killed ~36,000, produced global sunsets for years, and reshaped the island's geography.",
     "source": "Smithsonian Global Volcanism Program"},
    {"id": "land-tambora", "title": "Tambora Eruption / Year Without a Summer", "year": 1815,
     "lat": -8.25, "lng": 118.0, "category": "land", "region": "Indonesia",
     "summary": "Mt. Tambora's VEI-7 eruption cooled the planet, causing 1816's 'Year Without a Summer' with global crop failures.",
     "source": "Smithsonian Global Volcanism Program"},
    {"id": "land-dustbowl", "title": "American Dust Bowl", "year": 1934,
     "lat": 36.5, "lng": -100.0, "category": "land", "region": "US Great Plains",
     "summary": "Severe drought and poor farming practices caused massive dust storms across the U.S. plains, displacing hundreds of thousands.",
     "source": "US Library of Congress"},
    {"id": "land-aral", "title": "Aral Sea Desiccation Begins", "year": 1960,
     "lat": 45.0, "lng": 60.0, "category": "land", "region": "Central Asia",
     "summary": "Soviet irrigation projects diverted the Amu Darya and Syr Darya rivers, causing one of the world's largest lakes to shrink by ~90%.",
     "source": "NASA Earth Observatory"},

    # =========================
    # CIVILIZATIONS
    # =========================
    {"id": "civ-jericho", "title": "Jericho — Earliest Walled Town", "year": -9000,
     "lat": 31.87, "lng": 35.44, "category": "civilizations", "region": "Levant",
     "summary": "Neolithic Jericho, with its stone tower and walls, is among the oldest continuously inhabited settlements known.",
     "source": "UNESCO / British Museum"},
    {"id": "civ-catalhoyuk", "title": "Çatalhöyük Settlement", "year": -7100,
     "lat": 37.66, "lng": 32.83, "category": "civilizations", "region": "Anatolia",
     "summary": "A dense Neolithic proto-city in central Anatolia famous for its honeycomb houses and wall paintings.",
     "source": "UNESCO World Heritage"},
    {"id": "civ-sumer", "title": "Sumerian Cities of Mesopotamia", "year": -3500,
     "lat": 31.3, "lng": 45.6, "category": "civilizations", "region": "Mesopotamia",
     "summary": "Sumerians founded the first cities (Uruk, Ur, Eridu), invented cuneiform writing, the wheel, and codified law.",
     "source": "British Museum / Penn Museum"},
    {"id": "civ-egypt", "title": "Unification of Ancient Egypt", "year": -3100,
     "lat": 26.0, "lng": 32.0, "category": "civilizations", "region": "Nile Valley",
     "summary": "King Narmer unites Upper and Lower Egypt, founding a dynastic civilization that will endure for 3,000 years.",
     "source": "Smithsonian / Egyptian Museum Cairo"},
    {"id": "civ-indus", "title": "Indus Valley Civilization Peak", "year": -2600,
     "lat": 27.3, "lng": 68.1, "category": "civilizations", "region": "South Asia",
     "summary": "Harappa and Mohenjo-daro flourish with grid-planned cities, standardized weights, and advanced sanitation.",
     "source": "Archaeological Survey of India"},
    {"id": "civ-xia", "title": "Xia / Erlitou Culture in China", "year": -2070,
     "lat": 34.7, "lng": 112.6, "category": "civilizations", "region": "Yellow River",
     "summary": "The semi-legendary Xia and archaeologically confirmed Erlitou culture mark China's first Bronze Age state.",
     "source": "National Museum of China"},
    {"id": "civ-olmec", "title": "Olmec Civilization", "year": -1500,
     "lat": 17.9, "lng": -94.1, "category": "civilizations", "region": "Mesoamerica",
     "summary": "The 'mother culture' of Mesoamerica, famous for colossal stone heads and early ritual writing, influencing Maya and Aztec.",
     "source": "Smithsonian NMAI"},
    {"id": "civ-greece", "title": "Classical Athens & Democracy", "year": -500,
     "lat": 37.98, "lng": 23.72, "category": "civilizations", "region": "Aegean",
     "summary": "Cleisthenes' reforms establish Athenian democracy; philosophy, drama, and science flourish under Pericles.",
     "source": "British Museum / Ministry of Culture Greece"},
    {"id": "civ-rome", "title": "Roman Empire Founded", "year": -27,
     "lat": 41.9, "lng": 12.5, "category": "civilizations", "region": "Mediterranean",
     "summary": "Augustus becomes princeps, transforming the Roman Republic into an empire that will span three continents.",
     "source": "Musei Vaticani / British Museum"},
    {"id": "civ-han", "title": "Han Dynasty & Silk Road", "year": -130,
     "lat": 34.3, "lng": 108.9, "category": "civilizations", "region": "China",
     "summary": "Under Emperor Wu, Han China opens the Silk Road, linking East and West in the largest sustained trade network of antiquity.",
     "source": "National Museum of China"},
    {"id": "civ-maya", "title": "Maya Classic Period Peak", "year": 250,
     "lat": 17.2, "lng": -89.6, "category": "civilizations", "region": "Mesoamerica",
     "summary": "Maya city-states like Tikal and Palenque flourish with monumental architecture, astronomy, and hieroglyphic writing.",
     "source": "Smithsonian NMAI / INAH Mexico"},
    {"id": "civ-byzantium", "title": "Byzantine Empire Endures", "year": 527,
     "lat": 41.0, "lng": 28.98, "category": "civilizations", "region": "Anatolia",
     "summary": "Justinian I codifies Roman law, builds Hagia Sophia, and reconquers parts of the Western Mediterranean.",
     "source": "Dumbarton Oaks"},
    {"id": "civ-islam", "title": "Islamic Caliphate & Golden Age", "year": 750,
     "lat": 33.31, "lng": 44.36, "category": "civilizations", "region": "Middle East",
     "summary": "The Abbasid Caliphate makes Baghdad a center of science, translation, and mathematics — the House of Wisdom.",
     "source": "British Museum / Islamic Arts Museum"},
    {"id": "civ-tang", "title": "Tang Dynasty Flourishes", "year": 750,
     "lat": 34.3, "lng": 108.9, "category": "civilizations", "region": "China",
     "summary": "Tang China becomes the world's most populous, cosmopolitan empire, with Chang'an drawing traders from across Asia.",
     "source": "National Palace Museum Taipei"},
    {"id": "civ-vikings", "title": "Viking Age Expansion", "year": 800,
     "lat": 60.0, "lng": 10.0, "category": "civilizations", "region": "Scandinavia",
     "summary": "Norse seafarers raid, trade, and settle from Newfoundland to Constantinople, founding kingdoms in Ireland, Normandy, and Kievan Rus.",
     "source": "Nationalmuseet Denmark"},
    {"id": "civ-mongol", "title": "Mongol Empire Founded", "year": 1206,
     "lat": 47.9, "lng": 106.9, "category": "civilizations", "region": "Central Asia",
     "summary": "Genghis Khan unites the Mongol tribes, launching conquests that produce the largest contiguous land empire in history.",
     "source": "National Museum of Mongolia"},
    {"id": "civ-mali", "title": "Mali Empire under Mansa Musa", "year": 1324,
     "lat": 16.77, "lng": -3.0, "category": "civilizations", "region": "West Africa",
     "summary": "Mansa Musa's pilgrimage to Mecca displays Mali's staggering gold wealth; Timbuktu becomes a scholarly center.",
     "source": "UNESCO / Institut des Hautes Études de Tombouctou"},
    {"id": "civ-inca", "title": "Inca Empire (Tawantinsuyu)", "year": 1438,
     "lat": -13.5, "lng": -71.97, "category": "civilizations", "region": "Andes",
     "summary": "Pachacuti expands the Inca state into the largest pre-Columbian empire, with Cusco at its heart and Machu Picchu among its estates.",
     "source": "Ministerio de Cultura Perú"},
    {"id": "civ-aztec", "title": "Aztec Triple Alliance", "year": 1428,
     "lat": 19.43, "lng": -99.13, "category": "civilizations", "region": "Mesoamerica",
     "summary": "Tenochtitlán, Texcoco, and Tlacopan form the Triple Alliance, dominating central Mexico from lake-city Tenochtitlán.",
     "source": "INAH Mexico"},
    {"id": "civ-ottoman", "title": "Ottoman Conquest of Constantinople", "year": 1453,
     "lat": 41.0, "lng": 28.98, "category": "civilizations", "region": "Anatolia",
     "summary": "Mehmed II's cannons breach the Theodosian walls, ending the Byzantine Empire and reshaping Europe and the Middle East.",
     "source": "Topkapı Palace Museum"},
    {"id": "civ-usa", "title": "United States Declares Independence", "year": 1776,
     "lat": 39.95, "lng": -75.16, "category": "civilizations", "region": "North America",
     "summary": "Thirteen British colonies declare independence in Philadelphia, launching a modern republic founded on Enlightenment principles.",
     "source": "US National Archives"},
    {"id": "civ-ussr", "title": "Russian Revolution / USSR Founded", "year": 1917,
     "lat": 55.75, "lng": 37.62, "category": "civilizations", "region": "Eurasia",
     "summary": "Bolsheviks seize power, establishing the world's first communist state and reshaping 20th-century geopolitics.",
     "source": "Russian State Archives"},

    # =========================
    # PANDEMICS
    # =========================
    {"id": "pan-antonine", "title": "Antonine Plague", "year": 165,
     "lat": 41.9, "lng": 12.5, "category": "pandemics", "region": "Roman Empire",
     "summary": "Likely smallpox brought by returning legionaries kills ~5 million across the Roman world, straining the empire.",
     "source": "WHO / Cambridge Ancient History"},
    {"id": "pan-justinian", "title": "Plague of Justinian", "year": 541,
     "lat": 41.0, "lng": 28.98, "category": "pandemics", "region": "Byzantine",
     "summary": "The first recorded Yersinia pestis pandemic devastates Constantinople and the Mediterranean, killing tens of millions.",
     "source": "WHO / Dumbarton Oaks"},
    {"id": "pan-blackdeath", "title": "Black Death", "year": 1347,
     "lat": 43.7, "lng": 11.25, "category": "pandemics", "region": "Eurasia",
     "summary": "Bubonic plague sweeps from Central Asia along trade routes, killing an estimated 30–60% of Europe's population.",
     "source": "Wellcome Collection"},
    {"id": "pan-smallpox-am", "title": "Columbian Exchange Smallpox in the Americas", "year": 1520,
     "lat": 19.43, "lng": -99.13, "category": "pandemics", "region": "Americas",
     "summary": "European smallpox devastates Indigenous populations of the Americas — some estimates suggest 80–95% mortality over a century.",
     "source": "Smithsonian NMAI"},
    {"id": "pan-cocoliztli", "title": "Cocoliztli Epidemics in Mexico", "year": 1545,
     "lat": 19.43, "lng": -99.13, "category": "pandemics", "region": "Mesoamerica",
     "summary": "A hemorrhagic fever (likely Salmonella enterica Paratyphi C) kills millions in the Aztec territories.",
     "source": "Max Planck Institute / INAH"},
    {"id": "pan-cholera", "title": "First Cholera Pandemic", "year": 1817,
     "lat": 22.57, "lng": 88.36, "category": "pandemics", "region": "South Asia",
     "summary": "Beginning in the Ganges delta, cholera spreads globally via trade and pilgrimage, spurring modern public health.",
     "source": "WHO"},
    {"id": "pan-flu-1918", "title": "1918 Influenza Pandemic", "year": 1918,
     "lat": 39.1, "lng": -94.6, "category": "pandemics", "region": "Global",
     "summary": "H1N1 'Spanish flu' infects a third of humanity and kills an estimated 50 million in about 18 months.",
     "source": "US CDC / WHO"},
    {"id": "pan-hiv", "title": "HIV/AIDS Recognized", "year": 1981,
     "lat": 34.05, "lng": -118.24, "category": "pandemics", "region": "Global",
     "summary": "US CDC reports unusual pneumonia clusters in Los Angeles, marking the identification of the HIV/AIDS pandemic.",
     "source": "US CDC / UNAIDS"},
    {"id": "pan-covid", "title": "COVID-19 Pandemic", "year": 2020,
     "lat": 30.59, "lng": 114.31, "category": "pandemics", "region": "Global",
     "summary": "SARS-CoV-2 spreads worldwide from Wuhan, triggering the first pandemic in the age of genomics and global lockdowns.",
     "source": "WHO"},

    # =========================
    # TECHNOLOGIES
    # =========================
    {"id": "tech-fire", "title": "Controlled Use of Fire", "year": -400000,
     "lat": -1.0, "lng": 36.0, "category": "technology", "region": "East Africa",
     "summary": "Hearths at sites like Koobi Fora suggest hominins controlled fire, enabling cooking, warmth, and social gatherings.",
     "source": "Smithsonian Human Origins"},
    {"id": "tech-agri", "title": "Agriculture (Fertile Crescent)", "year": -10000,
     "lat": 34.5, "lng": 40.0, "category": "technology", "region": "Levant",
     "summary": "Wheat, barley, sheep and goats are domesticated in the Fertile Crescent, launching the Neolithic Revolution.",
     "source": "Smithsonian / FAO"},
    {"id": "tech-pottery", "title": "Pottery in East Asia", "year": -18000,
     "lat": 24.9, "lng": 118.6, "category": "technology", "region": "East Asia",
     "summary": "Xianrendong Cave in China holds some of the earliest known pottery, used by hunter-gatherers long before farming.",
     "source": "Peking University"},
    {"id": "tech-writing", "title": "Cuneiform Writing", "year": -3200,
     "lat": 31.3, "lng": 45.6, "category": "technology", "region": "Mesopotamia",
     "summary": "Sumerian temple accountants develop cuneiform on clay tablets — one of humanity's first writing systems.",
     "source": "British Museum"},
    {"id": "tech-wheel", "title": "The Wheel", "year": -3500,
     "lat": 47.0, "lng": 40.0, "category": "technology", "region": "Eurasian Steppe",
     "summary": "Potter's wheels and wheeled vehicles emerge in Mesopotamia and the steppes, revolutionizing craft and transport.",
     "source": "Smithsonian / British Museum"},
    {"id": "tech-bronze", "title": "Bronze Age Begins", "year": -3300,
     "lat": 37.0, "lng": 43.0, "category": "technology", "region": "Near East",
     "summary": "Copper is alloyed with tin to make bronze, transforming tools, weapons, and long-distance trade in metals.",
     "source": "British Museum"},
    {"id": "tech-iron", "title": "Iron Smelting", "year": -1200,
     "lat": 39.9, "lng": 32.85, "category": "technology", "region": "Anatolia",
     "summary": "Hittite metallurgists master iron smelting, ushering in the Iron Age and stronger tools and weapons.",
     "source": "Museum of Anatolian Civilizations"},
    {"id": "tech-alphabet", "title": "Phoenician Alphabet", "year": -1050,
     "lat": 33.9, "lng": 35.5, "category": "technology", "region": "Levant",
     "summary": "Phoenician traders spread a compact 22-letter alphabet — the ancestor of Greek, Latin, Arabic, and Hebrew scripts.",
     "source": "Louvre / National Museum of Beirut"},
    {"id": "tech-papermsk", "title": "Papermaking in China", "year": 105,
     "lat": 34.75, "lng": 113.62, "category": "technology", "region": "China",
     "summary": "Cai Lun refines papermaking at the Han court, spreading cheap writing material west along the Silk Road.",
     "source": "National Museum of China"},
    {"id": "tech-gunpowder", "title": "Gunpowder in China", "year": 850,
     "lat": 30.0, "lng": 111.0, "category": "technology", "region": "China",
     "summary": "Daoist alchemists searching for elixirs of life discover gunpowder, first used for fireworks and later warfare.",
     "source": "Needham Research Institute"},
    {"id": "tech-print-china", "title": "Movable-Type Printing (Bi Sheng)", "year": 1040,
     "lat": 32.05, "lng": 118.77, "category": "technology", "region": "China",
     "summary": "Bi Sheng invents ceramic movable-type printing in Song China, four centuries before Gutenberg.",
     "source": "National Library of China"},
    {"id": "tech-gutenberg", "title": "Gutenberg Printing Press", "year": 1440,
     "lat": 50.0, "lng": 8.27, "category": "technology", "region": "Europe",
     "summary": "Johannes Gutenberg's metal movable-type press in Mainz begins the print revolution that transforms Europe.",
     "source": "Gutenberg Museum Mainz"},
    {"id": "tech-steam", "title": "Watt Steam Engine", "year": 1769,
     "lat": 55.86, "lng": -4.25, "category": "technology", "region": "Britain",
     "summary": "James Watt's separate-condenser steam engine kicks off the Industrial Revolution, transforming manufacturing and transport.",
     "source": "Science Museum London"},
    {"id": "tech-electric", "title": "Electric Lightbulb / Grid", "year": 1879,
     "lat": 40.55, "lng": -74.33, "category": "technology", "region": "USA",
     "summary": "Edison's incandescent bulb and Menlo Park lab lead to the first electric utility grids in New York and London.",
     "source": "Smithsonian NMAH"},
    {"id": "tech-flight", "title": "Wright Brothers First Powered Flight", "year": 1903,
     "lat": 36.02, "lng": -75.67, "category": "technology", "region": "USA",
     "summary": "Orville and Wilbur Wright achieve the first sustained, controlled, powered heavier-than-air flight at Kitty Hawk.",
     "source": "Smithsonian Air & Space Museum"},
    {"id": "tech-antibiotic", "title": "Penicillin Discovered", "year": 1928,
     "lat": 51.51, "lng": -0.11, "category": "technology", "region": "Britain",
     "summary": "Alexander Fleming notices Penicillium mold killing bacteria at St. Mary's Hospital — the antibiotic era begins.",
     "source": "Wellcome Collection"},
    {"id": "tech-nuclear", "title": "Nuclear Fission Weaponized", "year": 1945,
     "lat": 34.4, "lng": 132.45, "category": "technology", "region": "Japan",
     "summary": "Atomic bombs are dropped on Hiroshima and Nagasaki, ending WWII and opening the nuclear age with lasting consequences.",
     "source": "Hiroshima Peace Memorial Museum"},
    {"id": "tech-transistor", "title": "Transistor Invented", "year": 1947,
     "lat": 40.68, "lng": -74.4, "category": "technology", "region": "USA",
     "summary": "Bardeen, Brattain, and Shockley at Bell Labs invent the transistor, foundation of every modern electronic device.",
     "source": "Smithsonian NMAH"},
    {"id": "tech-dna", "title": "DNA Double Helix", "year": 1953,
     "lat": 52.20, "lng": 0.12, "category": "technology", "region": "Britain",
     "summary": "Watson, Crick, Franklin, and Wilkins reveal the double-helix structure of DNA at Cambridge, launching molecular biology.",
     "source": "MRC Laboratory of Molecular Biology"},
    {"id": "tech-space", "title": "Sputnik / Space Age Begins", "year": 1957,
     "lat": 45.92, "lng": 63.34, "category": "technology", "region": "Kazakhstan",
     "summary": "The Soviet Union launches Sputnik 1 from Baikonur, the first artificial satellite — the space age begins.",
     "source": "Roscosmos / Smithsonian NASM"},
    {"id": "tech-moon", "title": "Moon Landing (Apollo 11)", "year": 1969,
     "lat": 28.57, "lng": -80.65, "category": "technology", "region": "USA/Moon",
     "summary": "Apollo 11 lifts off from Kennedy Space Center; Neil Armstrong and Buzz Aldrin become the first humans on the Moon.",
     "source": "NASA / Smithsonian NASM"},
    {"id": "tech-internet", "title": "ARPANET / Internet Foundations", "year": 1969,
     "lat": 34.07, "lng": -118.44, "category": "technology", "region": "USA",
     "summary": "ARPANET's first message is sent from UCLA to Stanford, laying the technical foundation of the modern internet.",
     "source": "Computer History Museum"},
    {"id": "tech-web", "title": "World Wide Web", "year": 1991,
     "lat": 46.23, "lng": 6.05, "category": "technology", "region": "Switzerland",
     "summary": "At CERN, Tim Berners-Lee publishes the first website, making hypertext accessible over the internet to everyone.",
     "source": "CERN"},
    {"id": "tech-smart", "title": "iPhone / Smartphone Era", "year": 2007,
     "lat": 37.33, "lng": -122.03, "category": "technology", "region": "USA",
     "summary": "Apple introduces the iPhone in Cupertino, catalyzing the smartphone era that reshapes communication and daily life.",
     "source": "Computer History Museum"},
    {"id": "tech-crispr", "title": "CRISPR Gene Editing", "year": 2012,
     "lat": 37.87, "lng": -122.26, "category": "technology", "region": "USA/Europe",
     "summary": "Doudna and Charpentier demonstrate CRISPR-Cas9 as a precise gene-editing tool, revolutionizing biology and medicine.",
     "source": "UC Berkeley / Nobel Committee"},
    {"id": "tech-ai", "title": "Large Language Models Mainstream", "year": 2022,
     "lat": 37.78, "lng": -122.41, "category": "technology", "region": "USA/Global",
     "summary": "ChatGPT's public release brings large language models into everyday use, accelerating the modern AI era.",
     "source": "Stanford HAI"},
]


def list_events():
    return EVENTS


def find_event(event_id: str):
    for e in EVENTS:
        if e["id"] == event_id:
            return e
    return None
